### ISSUE TITLE
Kein Ausgabemodul bzw. -code vorhanden

### ISSUE THREAD

**Issue by iceman-fx** [alexplusde/notification#8]
Teste gerade dieses Addon, da es ganz interessant klingt.
Leider wird aber nichts im Frontend angezeigt, da es kein Ausgabemodul gibt bzw. nichts automatisch eingebunden wird.

Auch steht in der Hilfe dazu leider auch nichts.

Wie erhält man denn die Ausgabe im FE?

**Comment by alxndr-w** [comment]
Es gibt Ausgabe-Fragmente.
